import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { readFileSync } from 'fs';

const manifest = JSON.parse(readFileSync('./manifest.json', 'utf8'));

const banner =
`/*
久久任务日历 (JiuJiu Tasks Calendar)
Version: ${manifest.version}
Author: JiuJiu
Description: 综合性日历插件，支持农历、节假日、任务管理、笔记管理等功能

This is a generated/bundled file by Esbuild.
If you want to view the source, please visit the plugin repository.
*/
`;

const prod = (process.argv[2] === "production");

// 直接使用build API，不使用context API
if (prod) {
    // 生产构建
    await esbuild.build({
        banner: {
            js: banner,
        },
        entryPoints: ["src/main.ts"],
        bundle: true,
        external: [
            "obsidian",
            "electron",
            "@codemirror/autocomplete",
            "@codemirror/collab",
            "@codemirror/commands",
            "@codemirror/language",
            "@codemirror/lint",
            "@codemirror/search",
            "@codemirror/state",
            "@codemirror/view",
            "@lezer/common",
            "@lezer/highlight",
            "@lezer/lr",
            ...builtinModules],
        format: "cjs",
        target: "es2018",
        logLevel: "info",
        sourcemap: false,
        treeShaking: true,
        outfile: "main.js",
        minify: true,
    });
    process.exit(0);
} else {
    // 开发构建 - 使用watch模式
    const context = await esbuild.context({
        banner: {
            js: banner,
        },
        entryPoints: ["src/main.ts"],
        bundle: true,
        external: [
            "obsidian",
            "electron",
            "@codemirror/autocomplete",
            "@codemirror/collab",
            "@codemirror/commands",
            "@codemirror/language",
            "@codemirror/lint",
            "@codemirror/search",
            "@codemirror/state",
            "@codemirror/view",
            "@lezer/common",
            "@lezer/highlight",
            "@lezer/lr",
            ...builtinModules],
        format: "cjs",
        target: "es2018",
        logLevel: "info",
        sourcemap: "inline",
        treeShaking: true,
        outfile: "main.js",
        minify: false,
    });
    await context.watch();
}
