name: Release Obsidian plugin

on:
  release:
    types: [created]

env:
  PLUGIN_NAME: jiujiu-tasks-calendar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Build
        id: build
        run: |
          npm install
          npm run build
          mkdir ${{ env.PLUGIN_NAME }}
          cp main.js manifest.json styles.css ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
          ls -la

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./main.js
            ./manifest.json
            ./styles.css
            ./${{ env.PLUGIN_NAME }}.zip
